/** Traduction anglaise de l'interface : la clé est le texte français (voir `i18n.ts`). */
export const EN: Record<string, string> = {
  "# ce que fait la boîte noire, sur cette machine": "# what the gate does, on this machine",
  "# lecture seule ; donnez-la à une clé dans « Clés des applications »": "# read-only; grant it to a key in “App keys”",
  "# lecture seule, clé « {keys} »": "# read-only, key “{keys}”",
  "# les deux premières lignes": "# the first two rows",
  "# une nouvelle ligne": "# a new row",
  "(FILARR_GATE_ADMIN_HOST, FILARR_GATE_ADMIN_PORT)": "(FILARR_GATE_ADMIN_HOST, FILARR_GATE_ADMIN_PORT)",
  ", jusqu'au lendemain ou au palier suivant.": ", until the next day or a higher plan.",
  ", ou la variable": ", or the variable",
  "1 an": "1 year",
  "1 · Le jeton de l'accès": "1 · The access token",
  "2 · Où vos logiciels la trouvent": "2 · Where your software finds it",
  "3 · Protéger cette interface": "3 · Protect this interface",
  "30 jours": "30 days",
  "7 jours": "7 days",
  "8 essais sur environ 10 h 30, délai doublé à chaque échec, puis abandon noté au journal": "8 attempts over about 10.5 hours, delay doubled after each failure, then given up and logged",
  "90 jours": "90 days",
  "AAAA-MM-JJ": "YYYY-MM-DD",
  "API Filarr": "Filarr API",
  "Accès": "Access",
  "Accès API": "API accesses",
  "Accès API pas encore ouverts": "API accesses not open yet",
  "Accès en pause": "Access paused",
  "Accès expiré": "Access expired",
  "Accès révoqué": "Access revoked",
  "Accès à cette interface": "Access to this interface",
  "Action": "Action",
  "Actions": "Actions",
  "Activer le serveur MCP (assistants IA, lecture seule)": "Enable the MCP server (AI assistants, read-only)",
  "Administration": "Administration",
  "Adresse": "Address",
  "Adresse appelée": "Target URL",
  "Adresse d'écoute": "Listen address",
  "Adresse refusée par Filarr": "Address refused by Filarr",
  "Adresses IP autorisées": "IP allow-lists",
  "Adresses autorisées": "Allowed addresses",
  "Ajouter": "Create",
  "Ajouter dans": "Create in",
  "Alerte de Filarr : {name} à {pct} % ({time})": "Filarr alert: {name} at {pct}% ({time})",
  "Annuler": "Cancel",
  "Aperçu des données": "Data preview",
  "Application": "Application",
  "Aucun (derrière un proxy)": "None (behind a proxy)",
  "Aucun webhook : « Nouveau webhook » pour prévenir un logiciel quand une ligne change.": "No webhook yet: use “New webhook” to notify your software when a row changes.",
  "Aucune base ouverte : ouvrez une base à cet accès dans Filarr.": "No database opened: open a database to this access in Filarr.",
  "Aucune base ouverte à ce jeton pour le moment.": "No database is opened to this token yet.",
  "Aucune clé : créez-en une par logiciel qui lit vos bases.": "No key yet: create one per piece of software that reads your databases.",
  "Aucune pour le moment.": "None yet.",
  "Avis de quota de Filarr": "Filarr quota notice",
  "Base": "Database",
  "Base sans manifeste": "Database without a manifest",
  "Base vide": "Empty database",
  "Bases": "Databases",
  "Bases dans cet accès": "Databases in this access",
  "Bases et points d'accès": "Databases and endpoints",
  "Bases ouvertes par ce jeton": "Databases opened by this token",
  "Bases par accès": "Databases per access",
  "Bases qu’un même jeton peut ouvrir.": "Databases a single token can open.",
  "Bases répliquées": "Replicated databases",
  "Blocs chiffrés et têtes reçus de Filarr.": "Encrypted blocks and heads received from Filarr.",
  "Brancher cette boîte noire sur Filarr": "Connect this gate to Filarr",
  "C'est noté": "Got it",
  "Ce mois-ci, pour tout le compte": "This month, for the whole account",
  "Ce que compte Filarr ce mois-ci": "What Filarr counts this month",
  "Ce que la vue décide": "What the view decides",
  "Ce qui se passe": "What happens",
  "Certificat (PEM)": "Certificate (PEM)",
  "Certificat (chemin PEM)": "Certificate (PEM path)",
  "Certificat HTTPS": "HTTPS certificate",
  "Ces requêtes ne sortent jamais de votre réseau : la boîte noire répond depuis sa copie déchiffrée.": "These requests never leave your network: the gate answers from its decrypted copy.",
  "Cet accès ne peut que lire cette base : son droit est « lecture seule » dans Filarr.": "This access can only read this database: its right is “read-only” in Filarr.",
  "Champ JSON": "JSON field",
  "Champs envoyés": "Fields sent",
  "Champs envoyés (vide : toute la ligne)": "Fields sent (empty: the whole row)",
  "Changements": "Changes",
  "Changements reçus": "Changes received",
  "Changer le mot de passe": "Change the password",
  "Chaque demande de blocs ou de changements à Filarr.": "Each request for blocks or changes to Filarr.",
  "Chaque requête servie et chaque échange avec Filarr. Gardé {days} jours sur cette machine, jamais envoyé ailleurs.": "Every request served and every exchange with Filarr. Kept {days} days on this machine, never sent anywhere.",
  "Chaque vue de la base devient un point d'accès : ses filtres, son tri et ses colonnes font le contrat.": "Each view of the database becomes an endpoint: its filters, sort and columns are the contract.",
  "Chargement…": "Loading…",
  "Chercher dans le journal": "Search the log",
  "Chiffrer la connexion (HTTPS, avec un certificat fourni)": "Encrypt the connection (HTTPS, with a provided certificate)",
  "Clé": "Key",
  "Clé privée (PEM)": "Private key (PEM)",
  "Clé privée (chemin PEM)": "Private key (PEM path)",
  "Clé « {name} » créée": "Key “{name}” created",
  "Clés autorisées": "Allowed keys",
  "Clés des applications": "App keys",
  "Clés des bases": "Database keys",
  "Code de mise en route": "Setup code",
  "Colonne": "Column",
  "Compte Filarr": "Filarr account",
  "Condition (SQL, sur les champs JSON de la ligne)": "Condition (SQL, on the row's JSON fields)",
  "Connexion…": "Connecting…",
  "Consommation et limites": "Usage and limits",
  "Continuent, sur la dernière copie reçue. Rien ne casse chez vos logiciels.": "Keep working on the last copy received. Nothing breaks for your software.",
  "Continuer": "Continue",
  "Copie locale": "Local copy",
  "Copier": "Copy",
  "Copier le point d'accès": "Copy the endpoint",
  "Copiez-la maintenant : elle ne sera plus montrée. La boîte noire n’en garde que l’empreinte.": "Copy it now: it will not be shown again. The gate only keeps its hash.",
  "Copié": "Copied",
  "Créer la clé": "Create the key",
  "Créer le webhook": "Create the webhook",
  "Créer une clé d'accès": "Create a passkey",
  "Dans Filarr, sur la base : « ··· » › « Ouvrir à une API ». Le jeton s'affiche une seule fois ; collez-le ici.": "In Filarr, on the database: “···” › “Open to an API”. The token is shown only once; paste it here.",
  "Dernier changement": "Last change",
  "Dernier usage": "Last used",
  "Dernière livraison": "Last delivery",
  "Description OpenAPI 3.1": "OpenAPI 3.1 description",
  "Devenue point d'accès": "Now an endpoint",
  "Documentation OpenAPI publique sur": "Public OpenAPI documentation at",
  "Droits": "Rights",
  "Durée": "Duration",
  "Débit maximal (requêtes / minute)": "Rate limit (requests / minute)",
  "Débit vers Filarr": "Rate towards Filarr",
  "Déchiffré sur cette machine. Rien de ce tableau n'est passé en clair chez Filarr.": "Decrypted on this machine. Nothing in this table went through Filarr in clear.",
  "Déclencheur": "Trigger",
  "Détail": "Detail",
  "Détail de la base": "Database detail",
  "Détail et paliers": "Details and plans",
  "Efface la copie, les clés dérivées, le jeton, les clés des applications, les webhooks et le journal. Les données restent dans Filarr ; pour couper l'accès partout, révoquez-le dans Filarr.": "Erases the copy, the derived keys, the token, the app keys, the webhooks and the log. The data stays in Filarr; to cut the access everywhere, revoke it in Filarr.",
  "Emplacement": "Location",
  "Empreinte du jeton": "Token fingerprint",
  "En direct": "Live",
  "Encore une fois": "Once more",
  "Enregistrer": "Save",
  "Enregistrer comme point d'accès": "Save as an endpoint",
  "Enregistré.": "Saved.",
  "Enregistré. L’API locale écoute maintenant à sa nouvelle adresse.": "Saved. The local API now listens at its new address.",
  "Envoi": "Sent",
  "Envoyer les métriques au format Prometheus sur /metrics": "Expose Prometheus metrics on /metrics",
  "Envoyer un essai": "Send a test",
  "Erreur": "Error",
  "Essai": "Attempt",
  "Expire": "Expires",
  "Explorateur SQL": "SQL explorer",
  "Exporter (JSON Lines)": "Export (JSON Lines)",
  "Exécuter": "Run",
  "Facturation": "Billing",
  "Facturation : nouvelle commande": "Billing: new order",
  "Faire confiance à X-Forwarded-For de": "Trust X-Forwarded-For from",
  "Fermer": "Close",
  "Fichier de réglages": "Settings file",
  "Filarr injoignable": "Filarr unreachable",
  "Filarr limite cet accès ({code}) : reprise à {time}. Les lectures locales continuent.": "Filarr is limiting this access ({code}): resuming at {time}. Local reads go on.",
  "Filarr ne compte que ce qui passe par lui. Les lectures servies d'ici sont illimitées, à tous les paliers.": "Filarr only counts what goes through it. Reads served from here are unlimited, on every plan.",
  "Filtre": "Filter",
  "Filtrer le journal": "Filter the log",
  "Format": "Format",
  "Fourni (chemins ci-dessous)": "Provided (paths below)",
  "Fourni : {path}": "Provided: {path}",
  "Gardez-le chez le destinataire : il vérifie chaque livraison. Il ne sera plus montré en entier.": "Keep it on the receiving side: it verifies each delivery. It will not be shown in full again.",
  "Générée à partir des vues et des colonnes. Postman, n8n, Make et les générateurs de bibliothèques la lisent directement.": "Generated from the views and columns. Postman, n8n, Make and client generators read it directly.",
  "Heure": "Time",
  "Il commence par flr_live_. Il n'est jamais envoyé à Filarr : la boîte noire en tire ses clés, et ne présente au serveur qu'une preuve.": "It starts with flr_live_. It is never sent to Filarr: the gate derives its keys from it and only presents a proof to the server.",
  "Interface de gestion": "Management interface",
  "Interface de gestion :": "Management interface:",
  "Intégrations": "Integrations",
  "Jeton": "Token",
  "Jeton d'accès": "Access token",
  "Jeton inconnu de Filarr": "Token unknown to Filarr",
  "Journal": "Log",
  "Journal des accès (Filarr)": "Access log (Filarr)",
  "Journal gardé": "Log kept",
  "L'API et cette interface écoutent ici. Par défaut, seulement cette machine.": "The API and this interface listen here. By default, this machine only.",
  "L'API sera joignable depuis le réseau sans chiffrement : mettez-la derrière un mandataire HTTPS, ou fournissez un certificat.": "The API will be reachable from the network without encryption: put it behind an HTTPS proxy, or provide a certificate.",
  "L'écriture devient un changement chiffré, validé par Filarr, visible tout de suite dans l'appli, sans conflit.": "The write becomes an encrypted change, validated by Filarr, visible right away in the app, without conflicts.",
  "L'écriture vers Filarr est éteinte sur cette boîte noire (Réglages › Liaison avec Filarr).": "Writing to Filarr is switched off on this gate (Settings › Link with Filarr).",
  "L'écriture vers Filarr est éteinte sur cette boîte noire : les cases Ajouter, Modifier et Supprimer apparaîtront quand elle sera allumée (Réglages).": "Writing to Filarr is switched off on this gate: the Create, Update and Delete boxes appear once it is on (Settings).",
  "La boîte noire ne répond pas : {error}": "The gate does not answer: {error}",
  "Langue": "Language",
  "Le barème public de Filarr (/public/api-limits) ne répond pas : seules les limites de cet accès sont connues.": "Filarr's public plan table (/public/api-limits) does not answer: only this access's limits are known.",
  "Le jeton vient de FILARR_GATE_TOKEN : changez la variable pour le remplacer.": "The token comes from FILARR_GATE_TOKEN: change the variable to replace it.",
  "Le mot de passe vient de FILARR_GATE_ADMIN_PASSWORD.": "The password comes from FILARR_GATE_ADMIN_PASSWORD.",
  "Le moteur SQL de Filarr, sur la copie déchiffrée. Lecture seule : les écritures passent par les points d'accès.": "Filarr's SQL engine, on the decrypted copy. Read-only: writes go through the endpoints.",
  "Lectures": "Reads",
  "Lectures locales": "Local reads",
  "Lectures servies localement": "Reads served locally",
  "Les bases ouvertes par ce jeton, sous leur nom SQL.": "The databases opened by this token, under their SQL names.",
  "Les clés d'accès (passkeys) ne sont pas encore prises en charge : cette interface est protégée par mot de passe.": "Passkeys are not supported yet: this interface is protected by a password.",
  "Les compteurs sont tenus par Filarr : tous les accès API du compte les partagent.": "The counters are kept by Filarr: all the account's API accesses share them.",
  "Les lignes « Filarr » viennent de la liaison chiffrée : synchro des blocs, rescellement des clés, refus de quota. Le reste ne quitte pas votre réseau.": "“Filarr” lines come from the encrypted link: block sync, key resealing, quota refusals. Everything else stays in your network.",
  "Les noms de champs suivent les colonnes ; renommer une colonne dans Filarr garde l'ancien nom, pour que vos logiciels ne cassent pas. Une relation vers une base que ce jeton n'ouvre pas rend les identifiants bruts, et ses agrégats valent null.": "Field names follow the columns; renaming a column in Filarr keeps the old name so your software does not break. A relation to a database this token does not open returns raw ids, and its aggregates are null.",
  "Les nouveaux blocs attendent le 1er du mois ; la copie reste servie.": "New blocks wait for the 1st of the month; the copy keeps being served.",
  "Liaison avec Filarr": "Link with Filarr",
  "Ligne": "Row",
  "Ligne ajoutée": "Row added",
  "Ligne modifiée": "Row updated",
  "Ligne supprimée": "Row deleted",
  "Lignes": "Rows",
  "Limite": "Limit",
  "Limité par Filarr": "Limited by Filarr",
  "Lire": "Read",
  "Lire toutes les bases": "Read all databases",
  "Mettre en pause": "Pause",
  "Mise à jour": "Updating",
  "Mise à jour requise": "Update required",
  "Mises à jour": "Updates",
  "Modifier": "Update",
  "Modifier dans": "Update in",
  "Mot de passe": "Password",
  "Mot de passe (dix caractères au moins)": "Password (at least ten characters)",
  "Mot de passe actuel": "Current password",
  "Mot de passe changé.": "Password changed.",
  "Méthodes": "Methods",
  "Métriques Prometheus sur": "Prometheus metrics on",
  "Navigation de Filarr Gate": "Filarr Gate navigation",
  "Ne rien garder sur le disque, même chiffré (plus lent au redémarrage ; pris en compte au prochain démarrage)": "Keep nothing on disk, even encrypted (slower restarts; applied at the next start)",
  "Nom": "Name",
  "Nom de la requête (il donne le chemin /v1/q/…)": "Query name (it gives the /v1/q/… path)",
  "Nouveau jeton en service.": "New token in use.",
  "Nouveau mot de passe": "New password",
  "Nouveau webhook": "New webhook",
  "Nouvelle clé": "New key",
  "OpenAPI": "OpenAPI",
  "Oublier cette machine": "Forget this machine",
  "Ouvrir le tableau de bord": "Open the dashboard",
  "Ouvrir les points d'accès": "Open the endpoints",
  "Pages web autorisées (CORS)": "Allowed web pages (CORS)",
  "Par accès. Ne bride pas les lectures locales.": "Per access. Does not throttle local reads.",
  "Par palier": "By plan",
  "Pas encore disponible dans cette version": "Not available in this version yet",
  "Passe en relève toutes les 15 minutes jusqu’au mois suivant.": "Switches to polling every 15 minutes until next month.",
  "Point d'accès": "Endpoint",
  "Points d'accès": "Endpoints",
  "Port": "Port",
  "Protection": "Protection",
  "Prévenu": "Notified",
  "Quand une ligne change dans Filarr, la boîte noire la déchiffre et prévient vos logiciels. Le contenu ne passe jamais en clair par Filarr.": "When a row changes in Filarr, the gate decrypts it and notifies your software. The content never goes through Filarr in clear.",
  "Quand une limite est atteinte": "When a limit is reached",
  "Qui entre ici lit les données en clair. Les clés d'accès résistent à l'hameçonnage.": "Whoever gets in here reads the data in clear. Passkeys resist phishing.",
  "Qui gère la boîte noire voit les données en clair. Entrez le mot de passe posé à la mise en route.": "Whoever manages the gate sees the data in clear. Enter the password set during setup.",
  "Qui gère la boîte noire voit les données en clair. Une clé d'accès (passkey) ou un mot de passe la protège.": "Whoever manages the gate sees the data in clear. A passkey or a password protects it.",
  "Refus et erreurs": "Refusals and errors",
  "Refuser les requêtes d'une page web (CORS fermé)": "Refuse requests from web pages (CORS closed)",
  "Refusées en 429 avec": "Refused with 429 and",
  "Relations à résoudre": "Relations to resolve",
  "Relève périodique": "Polling",
  "Remplacer": "Replace",
  "Remplacer le jeton": "Replace the token",
  "Renouveler le secret ? Le destinataire devra recevoir le nouveau.": "Renew the secret? The receiver will need the new one.",
  "Reprendre": "Resume",
  "Reprises": "Retries",
  "Requête": "Query",
  "Requêtes (24 h)": "Requests (24 h)",
  "Requêtes de synchro": "Sync requests",
  "Requêtes enregistrées": "Saved queries",
  "Requêtes par minute sur la dernière heure": "Requests per minute over the last hour",
  "Requêtes servies (24 h)": "Requests served (24 h)",
  "Resynchronisation faite.": "Resync done.",
  "Resynchroniser tout": "Resync everything",
  "Retour": "Back",
  "Rien n’est encore parti.": "Nothing sent yet.",
  "Rien pour ce filtre.": "Nothing for this filter.",
  "Réglages": "Settings",
  "Réponse": "Response",
  "Réponse depuis la copie en mémoire : pas d'aller-retour vers Filarr.": "Answered from the in-memory copy: no round trip to Filarr.",
  "Réseau": "Network",
  "Résultat": "Result",
  "Révoquer": "Revoke",
  "Révoquer la clé « {name} » ? Elle cesse de répondre tout de suite.": "Revoke the key “{name}”? It stops working right away.",
  "SELECT, jointures, regroupements": "SELECT, joins, grouping",
  "SQL en lecture (/v1/sql) sur les bases qu’elle lit": "Read-only SQL (/v1/sql) on the databases it reads",
  "Sans interface :": "Without the interface:",
  "Sans jeton": "No token",
  "Santé de la boîte noire": "Gate health",
  "Schéma": "Schema",
  "Se connecter": "Sign in",
  "Se déconnecter": "Sign out",
  "Secret de signature": "Signing secret",
  "Serveur MCP (assistants IA)": "MCP server (AI assistants)",
  "Déposer des fichiers (POST /v1/files)": "Deposit files (POST /v1/files)",
  "Serveur MCP pour les assistants IA (lecture seule, par clé)": "MCP server for AI assistants (read-only, per key)",
  "Seulement quand la condition DEVIENT vraie (« statut devient Perdu »)": "Only when the condition BECOMES true (“status becomes Lost”)",
  "Seuls les échanges avec Filarr sont comptés. Les lectures servies par la boîte noire sont illimitées.": "Only exchanges with Filarr are counted. Reads served by the gate are unlimited.",
  "Signature": "Signature",
  "Source": "Source",
  "Stockage local": "Local storage",
  "Supprimer": "Delete",
  "Supprimer dans": "Delete in",
  "Supprimer la requête « {name} » ? Son point d’accès cessera de répondre.": "Delete the query “{name}”? Its endpoint will stop answering.",
  "Supprimer le webhook « {name} » ?": "Delete the webhook “{name}”?",
  "Supprimer {name}": "Delete {name}",
  "Synchro": "Sync",
  "Synchronisé avec Filarr": "Synced with Filarr",
  "Tableau de bord": "Dashboard",
  "Tables": "Tables",
  "Taille": "Size",
  "Tapez « oublier » pour confirmer": "Type “oublier” to confirm",
  "Texte SQL": "SQL text",
  "Tout": "All",
  "Tout effacer ici": "Erase everything here",
  "Tout gérer": "Manage all",
  "Tout se déchiffre ici, sur votre serveur. Filarr ne voit que des blocs chiffrés.": "Everything is decrypted here, on your server. Filarr only sees encrypted blocks.",
  "Tout se règle aussi par fichier": "Everything can also be set in a file",
  "Toute la base": "The whole database",
  "Toutes les bases et vues": "All databases and views",
  "Traces OpenTelemetry (pas encore disponible)": "OpenTelemetry traces (not available yet)",
  "Trafic local, dernière heure": "Local traffic, last hour",
  "Trois étapes. Le jeton reste sur cette machine : c'est lui qui ouvre les bases, et Filarr n'en garde qu'une empreinte.": "Three steps. The token stays on this machine: it opens the databases, and Filarr only keeps a fingerprint of it.",
  "Type dans Filarr": "Type in Filarr",
  "Télécharger l'OpenAPI": "Download the OpenAPI",
  "Un horodatage de plus de 5 minutes se refuse.": "Reject a timestamp older than 5 minutes.",
  "Un jeton est déjà fourni à cette boîte noire (variable FILARR_GATE_TOKEN ou commande init).": "A token is already provided to this gate (FILARR_GATE_TOKEN variable or the init command).",
  "Une clé révoquée cesse de répondre tout de suite. Elle ne touche pas au jeton Filarr : pour couper la boîte noire elle-même, révoquez l’accès dans Filarr.": "A revoked key stops working right away. It does not touch the Filarr token: to cut the gate itself off, revoke the access in Filarr.",
  "Une requête enregistrée se sert comme une vue, mise à jour à chaque changement de la base.": "A saved query is served like a view, updated on each change of the database.",
  "Utiliser un mot de passe": "Use a password",
  "Valeurs": "Values",
  "Validations du jour": "Commits today",
  "Version": "Version",
  "Voir le journal": "See the log",
  "Volume": "Volume",
  "Volume descendu": "Downloaded volume",
  "Vos logiciels n'ont jamais le jeton Filarr : chacun reçoit sa clé, limitée aux points d'accès qu'il lui faut.": "Your software never gets the Filarr token: each one gets its own key, limited to the endpoints it needs.",
  "Vous n'êtes pas sur la machine de la boîte noire : saisissez le code affiché dans sa console (ou `docker logs`).": "You are not on the gate's machine: enter the code shown in its console (or `docker logs`).",
  "Vue (facultatif : seules ses lignes déclenchent)": "View (optional: only its rows trigger)",
  "Vue dans Filarr": "View in Filarr",
  "Vérification…": "Checking…",
  "Vérifier le jeton": "Check the token",
  "Vérifiez la signature sur le corps brut, avant de le lire :": "Verify the signature on the raw body before reading it:",
  "Webhooks": "Webhooks",
  "Webhooks livrés (24 h)": "Webhooks delivered (24 h)",
  "accès « {name} »": "access “{name}”",
  "actif": "active",
  "active": "active",
  "agrégat": "rollup",
  "aucune (CORS fermé)": "none (CORS closed)",
  "aucune clé détenue": "no key held",
  "aucune livraison": "no delivery",
  "aussi servie sur /openapi.json": "also served at /openapi.json",
  "base non ouverte": "database not opened",
  "blocs chiffrés sur disque · lignes en mémoire": "encrypted blocks on disk · rows in memory",
  "blocs chiffrés sur disque, lignes déchiffrées en mémoire seulement": "encrypted blocks on disk, decrypted rows in memory only",
  "calculé": "computed",
  "case à cocher": "checkbox",
  "chargement…": "loading…",
  "clé manquante": "key missing",
  "clé, chemin, code…": "key, path, code…",
  "clés de l'accès dérivées": "access keys derived",
  "clés détenues {keys}": "keys held {keys}",
  "dans 1 an": "in 1 year",
  "dans 90 jours": "in 90 days",
  "dans Docker.": "in Docker.",
  "date": "date",
  "date de création": "created time",
  "date de modification": "updated time",
  "dernier changement {ago}": "last change {ago}",
  "devient vrai : ": "becomes true: ",
  "e-mail": "email",
  "en attente (limite)": "waiting (limit)",
  "en cours": "in progress",
  "en direct": "live",
  "en direct (connexion permanente)": "live (permanent connection)",
  "en pause": "paused",
  "en {s} s": "in {s} s",
  "erreur": "error",
  "expire le {date}": "expires on {date}",
  "expirée": "expired",
  "fichier du coffre": "vault file",
  "fixé par gate.toml": "set by gate.toml",
  "fixé par {name}": "set by {name}",
  "formule": "formula",
  "hors ligne": "offline",
  "identifiants de lignes": "row ids",
  "illimitées": "unlimited",
  "jamais": "never",
  "jeton reconnu par Filarr": "token recognised by Filarr",
  "la boîte noire · v{version}": "the gate · v{version}",
  "lecture": "read",
  "lecture et écriture": "read and write",
  "lecture seule": "read-only",
  "lecture seulement, y compris les bases ouvertes plus tard": "read only, including databases opened later",
  "lien": "link",
  "ligne": "row",
  "lignes": "rows",
  "lues en mémoire · médiane {ms} ms": "read from memory · median {ms} ms",
  "magasin": "store",
  "mois remis à zéro le {date}": "month resets on {date}",
  "nombre": "number",
  "non": "no",
  "non (base en lecture)": "no (read-only database)",
  "non résolu": "unresolved",
  "non vérifiée": "not verified",
  "note": "rating",
  "note liée": "linked note",
  "ou par variables d'environnement, pour Docker et les déploiements scriptés.": "or with environment variables, for Docker and scripted deployments.",
  "ou une image Docker plus récente": "or a newer Docker image",
  "oui": "yes",
  "palier {tier}": "{tier} plan",
  "personne": "person",
  "pointe {peak} / {max} par minute": "peak {peak} / {max} per minute",
  "premier lancement": "first launch",
  "proche du débit": "near rate limit",
  "progression": "progress",
  "refusée par Filarr": "refused by Filarr",
  "relation": "relation",
  "relations résolues ({list})": "relations resolved ({list})",
  "relève toutes les {n} s": "polling every {n} s",
  "relève {n} min": "polling {n} min",
  "renouveler": "renew",
  "requêtes / minute": "requests / minute",
  "résultat tronqué à 10 000 lignes": "result truncated to 10,000 rows",
  "sans aller-retour": "no round trip",
  "secret": "secret",
  "sélection": "select",
  "sélection multiple": "multi-select",
  "table de liaison ou base non ouverte": "join table or database not opened",
  "tapez « oublier »": "type “oublier”",
  "texte": "text",
  "tout en mémoire": "everything in memory",
  "tout en mémoire (rien sur le disque)": "everything in memory (nothing on disk)",
  "toute la base": "the whole database",
  "toute la ligne": "the whole row",
  "toutes (ou 10.0.4.0/24, …)": "all (or 10.0.4.0/24, …)",
  "toutes adresses": "all addresses",
  "toutes les lignes": "all rows",
  "toutes les lignes, ordre manuel": "all rows, manual order",
  "tri : {list}": "sort: {list}",
  "téléphone": "phone",
  "valide · expire le {date}": "valid · expires on {date}",
  "valide · sans échéance": "valid · no expiry",
  "version": "version",
  "vue Requête (SQL)": "Query view (SQL)",
  "{bytes} chiffrés reçus": "{bytes} encrypted received",
  "{code} · abandon": "{code} · given up",
  "{code} · nouvel essai à {time}": "{code} · retrying at {time}",
  "{events} dans {base}": "{events} in {base}",
  "{n} / jour": "{n} / day",
  "{n} / min": "{n} / min",
  "{n} / mois": "{n} / month",
  "{n} abandon(s)": "{n} given up",
  "{n} base ouverte": "{n} database opened",
  "{n} bases ouvertes": "{n} databases opened",
  "{n} bloc": "{n} block",
  "{n} bloc chiffré reçu": "{n} encrypted block received",
  "{n} blocs": "{n} blocks",
  "{n} blocs chiffrés reçus": "{n} encrypted blocks received",
  "{n} colonne": "{n} column",
  "{n} colonnes": "{n} columns",
  "{n} conflit(s) rejoué(s) · validées par le serveur": "{n} conflict(s) replayed · validated by the server",
  "{n} en reprise": "{n} retrying",
  "{n} filtre": "{n} filter",
  "{n} filtres": "{n} filters",
  "{n} jours": "{n} days",
  "{n} ligne": "{n} row",
  "{n} ligne déchiffrée": "{n} row decrypted",
  "{n} lignes": "{n} rows",
  "{n} lignes déchiffrées": "{n} rows decrypted",
  "{n} lignes parcourues en {ms} ms": "{n} rows scanned in {ms} ms",
  "{n} livrés en 24 h · {p} en reprise": "{n} delivered in 24 h · {p} retrying",
  "{n} vue": "{n} view",
  "{n} vues": "{n} views",
  "{shown} lignes montrées sur {total}": "{shown} rows shown out of {total}",
  "À 80 % puis à 100 %, ici, dans Filarr et par webhook": "At 80% then 100%, here, in Filarr and by webhook",
  "Écrire": "Write",
  "Écrire vers Filarr (droit « lecture et écriture » de l’accès requis)": "Write to Filarr (requires the access's “read and write” right)",
  "Écriture": "Write",
  "Écriture (validations)": "Writes (commits)",
  "Écritures": "Writes",
  "Écritures du jour": "Writes today",
  "Écritures envoyées à Filarr ; une validation peut porter plusieurs lignes, Filarr ne les voit pas. Remis à zéro à minuit UTC.": "Writes sent to Filarr; one commit may carry several rows, Filarr cannot see them. Reset at midnight UTC.",
  "Écritures vers Filarr (24 h)": "Writes to Filarr (24 h)",
  "État": "State",
  "Événement": "Event",
  "à jour": "up to date",
  "écoute locale seulement": "local only",
  "époque {e} · génération {g}": "epoch {e} · generation {g}",
  "Aucun dépôt pour l’instant.": "No deposits yet.",
  "Aucune boîte de dépôt n’est liée à cet accès. Liez-en une dans Filarr : Réglages › Accès API › Recevoir des fichiers.": "No drop box is linked to this access. Link one in Filarr: Settings › API accesses › Receive files.",
  "Aucune synchro ne désigne cette boîte noire. Elles se créent dans Filarr : « ··· » d’une base › « Alimenter depuis une base externe… ».": "No sync points to this gate. Syncs are created in Filarr: a database’s “···” › “Feed from an external database…”.",
  "Boîte de dépôt": "Drop box",
  "Ce mois-ci (compte entier)": "This month (whole account)",
  "Clé de {host}": "Key for {host}",
  "Clé donnée par l’environnement ou gate.toml ({env}).": "Key given by the environment or gate.toml ({env}).",
  "Colonnes instables (elles ne sortent plus) : {cols}": "Unstable columns (no longer sent out): {cols}",
  "Connecteur": "Connector",
  "Dernier passage": "Last run",
  "Déposer un fichier d’essai": "Deposit a test file",
  "Déposé": "Deposited",
  "Dépôt": "Deposit",
  "En attente de rangement": "Waiting to be filed",
  "Extensions refusées : {list}": "Refused extensions: {list}",
  "Fichiers reçus": "Received files",
  "Filtre (avant tout envoi)": "Filter (before anything is sent)",
  "Fréquence": "Frequency",
  "Journal de la synchro": "Sync log",
  "La clé du créateur de l’accès n’est pas authentifiée : aucune synchro ne s’exécute. Remplacez le jeton depuis Filarr (bureau ou web).": "The access creator’s key is not authenticated: no sync runs. Replace the token from Filarr (desktop or web).",
  "Lancer maintenant": "Run now",
  "Les bases externes que Filarr confie à cette boîte noire. Elle les synchronise à la fréquence choisie dans Filarr, avec la clé donnée ici.": "The external databases Filarr hands to this gate. It syncs them at the frequency chosen in Filarr, with the key given here.",
  "Prochain passage": "Next run",
  "Rangé": "Filed",
  "Rangée chiffrée sur cette machine, jamais envoyée à Filarr. Variable possible : {env}.": "Stored encrypted on this machine, never sent to Filarr. Possible variable: {env}.",
  "Refusés par la boîte noire, sans que rien ne parte : les exécutables et scripts, par extension et par signature, et les fichiers trop lourds. Réglable dans Réglages ou gate.toml (files_deny, files_allow, files_max_bytes).": "Refused by the gate before anything leaves: executables and scripts, by extension and by signature, and files that are too large. Adjustable in Settings or gate.toml (files_deny, files_allow, files_max_bytes).",
  "Retirer": "Remove",
  "Sens": "Direction",
  "Seules ces extensions passent : {list}": "Only these extensions pass: {list}",
  "Signature du créateur": "Creator’s signature",
  "Signée par": "Signed by",
  "Sources": "Sources",
  "Statut": "Status",
  "Taille maximale": "Maximum size",
  "Vos logiciels déposent des fichiers par POST /v1/files. La boîte noire les chiffre pour la boîte de dépôt liée ; votre appli Filarr les range. Ni Filarr ni cette boîte ne savent où.": "Your software deposits files with POST /v1/files. The gate encrypts them for the linked drop box; your Filarr app files them. Neither Filarr nor this gate knows where.",
  "boîte de dépôt non signée": "drop box not signed",
  "chaque jour": "every day",
  "clé du créateur non authentifiée": "creator key not authenticated",
  "clé enregistrée (chiffrée)": "key stored (encrypted)",
  "connecteur indisponible ici": "connector not available here",
  "dans les deux sens": "two-way",
  "dernier réussi {when}": "last success {when}",
  "définition invalide": "invalid definition",
  "définition plus récente que cette version": "definition newer than this version",
  "en attente de la signature du créateur": "waiting for the creator’s signature",
  "en attente de rangement": "waiting to be filed",
  "expiré": "expired",
  "import ponctuel": "one-off import",
  "jamais lancée": "never run",
  "jeton, mot de passe ou JSON du compte de service": "token, password or service account JSON",
  "miroir entrant": "inbound mirror",
  "palier insuffisant (Solo et plus)": "plan too low (Solo and up)",
  "politique de conflit à choisir dans Filarr": "conflict policy to choose in Filarr",
  "prête": "ready",
  "publication sortante": "outbound publishing",
  "question posée dans Filarr": "question asked in Filarr",
  "rangé": "filed",
  "refusé par l’appli": "rejected by the app",
  "révision {rev}": "revision {rev}",
  "toutes les 15 min": "every 15 min",
  "toutes les heures": "every hour",
  "vérifiée": "verified",
  "{n} conflits attendent votre décision : ils se tranchent dans Filarr. Ces cellules gardent leur valeur dans Filarr jusque-là ; le reste se synchronise.": "{n} conflicts are waiting for your decision: they are settled in Filarr. These cells keep their Filarr value until then; everything else keeps syncing.",
  "{n} conflits à trancher": "{n} conflicts to settle",
  "{n} fichiers · {bytes}": "{n} files · {bytes}",
  "{n} sur {max}": "{n} of {max}",
  "{rows} lignes · vers Filarr {inn} · vers la source {out}": "{rows} rows · into Filarr {inn} · into the source {out}",
  "à la demande": "on demand",
};
