/**
 * La documentation GÉNÉRÉE, et les contrôles qui gardent honnête la partie écrite à la main.
 *
 *   npm run docs          réécrit les fichiers générés et les blocs de code recopiés d'examples/
 *   npm run docs:check    ne change rien ; liste chaque écart et sort en 1 (rejoué par `npm test`)
 *
 * Générés : docs/reference/configuration.md, docs/reference/cli.md, docs/reference/errors.md,
 * docs/openapi/filarr-gate.v1.json, et les tables de docs/troubleshooting*.md.
 * Contrôlés : chaque bloc `<!-- snippet: … -->` égale sa région dans examples/, chaque lien relatif
 * mène quelque part, chaque nom FILARR_GATE_* existe dans le code, et aucun quota de palier n'est
 * écrit en chiffres (les quotas se lisent chez Filarr, `GET /public/api-limits`).
 *
 * Le texte produit est en anglais (la référence du dépôt public) ; les explications des codes
 * vivent dans codes.ts (anglais) et codes.fr.ts (français, pour le dépannage en français).
 */

import { spawnSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { DEFAULTS, ENV, TOML, MIN_POLL_SECONDS, type SettingKey } from '../../packages/server/src/settings';
import { DEFAULT_DENIED_EXTENSIONS, MAX_FILE_BYTES } from '../../packages/core/src/engine/gate/files';
import { BASE_PROBLEMS, FILARR_REV2, FILARR_REV3, LINK_STATES, LOCAL_CODES, PASSED_THROUGH, SYNC_CODES, type CodeText } from './codes';
import { FILARR_REV3_FR, LINK_STATES_FR } from './codes.fr';
import { genericOpenApi } from './openapi';
import { baseProblemCodes, knownEnvNames, linkStates, localApiCodes, rel, ROOT, syncCodes, vectorCodes } from './scan';

// ==================== Configuration ====================

const SETTING_TEXT: Record<SettingKey, string> = {
  apiUrl: 'The Filarr API. Change it only for a local Filarr (tests, the Filarr bench).',
  host: 'Address the local API listens on. `0.0.0.0` to accept other machines (the Docker image sets it).',
  port: 'Port of the local API.',
  adminHost: 'Address of the management UI. Keep `127.0.0.1` unless a protected proxy stands in front: whoever enters the UI reads the data.',
  adminPort: 'Port of the management UI.',
  write: 'Writes to Filarr through `POST`, `PATCH`, `DELETE`. Off by default; Filarr must also give the access a `rw` right and the plan must allow writes.',
  tlsCert: 'HTTPS for the local API: path of the certificate (PEM). Both `tls_cert` and `tls_key`, or neither.',
  tlsKey: 'HTTPS for the local API: path of the private key (PEM).',
  corsOrigins: 'Web pages allowed to call the API from a browser (`https://shop.example.com`), separated by commas. Empty: every request that carries an `Origin` is refused. `*` allows every page (avoid it).',
  trustProxy: 'Addresses or ranges of reverse proxies whose `X-Forwarded-For` is believed (for IP allow-lists and the log).',
  metrics: 'Prometheus metrics at `/metrics` (no key).',
  mcp: 'The MCP server at `/mcp`, for AI assistants (read only, keys with the MCP right).',
  docs: '`/openapi.json` and `/docs` without a key. Off: a key is needed to read them.',
  journalDays: 'Days the local log is kept (1 to 3650).',
  cache: '`disk`: encrypted blocks are kept in the state directory between restarts. `memory`: nothing on disk, not even encrypted blocks (the copy is downloaded again at each start).',
  pollSeconds: `Polling interval without the live stream, in seconds. Never below ${MIN_POLL_SECONDS}, and never faster than the plan allows.`,
  filesMaxBytes: `File slot: largest file accepted, in bytes. Lower than Filarr's limit if you like, never higher (at most ${MAX_FILE_BYTES}).`,
  filesDeny: 'File slot: extensions refused, separated by commas. Replacing the default list removes its entries: keep them.',
  filesAllow: 'File slot: if set, ONLY these extensions pass (executable signatures are refused anyway).',
  notify: 'Accept Filarr\'s push wake-ups at `/_filarr/notify` (signed with a key derived from the token).',
};

const mdValue = (key: SettingKey): string => {
  const v = DEFAULTS[key];
  if (key === 'filesDeny') return 'the contract list (below)';
  if (key === 'filesMaxBytes') return `\`${v}\` (100 MiB)`;
  if (Array.isArray(v)) return v.length === 0 ? 'none' : `\`${v.join(',')}\``;
  if (v === null) return 'none';
  return `\`${String(v)}\``;
};

function configurationMd(): string {
  const keys = Object.keys(DEFAULTS) as SettingKey[];
  const tomlOf = (k: SettingKey) => Object.entries(TOML).find(([, v]) => v === k)?.[0] ?? '';
  const rows = keys.map((k) => `| \`${ENV[k]}\` | \`${tomlOf(k)}\` | ${mdValue(k)} | ${SETTING_TEXT[k]} |`);
  return `<!-- Generated by \`npm run docs\` from packages/server/src/settings.ts: do not edit by hand. -->

# Configuration

A setting comes from, in this order (the first one found wins):

1. an **environment variable** (on Cloudflare: a Worker variable or secret);
2. the **\`gate.toml\`** file: \`$FILARR_GATE_STATE_DIR/gate.toml\`, or the file named by \`FILARR_GATE_CONFIG\`;
3. the **management UI** (Settings screen), saved in the state directory;
4. the default value.

A setting fixed by the environment or by \`gate.toml\` is shown **locked** in the UI.

## Settings

| environment variable | \`gate.toml\` | default | what it does |
|---|---|---|---|
${rows.join('\n')}

Booleans accept \`true\`, \`false\`, \`1\`, \`0\`, \`yes\`, \`no\`, \`on\`, \`off\`. Lists are separated by commas in a variable, and written as arrays in \`gate.toml\`.

The default list of refused extensions (\`files_deny\`): ${DEFAULT_DENIED_EXTENSIONS.map((e) => `\`${e}\``).join(', ')}.

## Other variables

| variable | what it does |
|---|---|
| \`FILARR_GATE_TOKEN\` | The access token (\`flr_live_…\`). Given this way, it is never written to disk. Otherwise \`filarr-gate init\` or the setup screen stores it in the state directory (file \`token\`, mode 0600). |
| \`FILARR_GATE_ADMIN_PASSWORD\` | The management password, instead of the one chosen on the setup screen (10 characters at least). |
| \`FILARR_GATE_STATE_DIR\` | The state directory: \`~/.filarr-gate\` by default, \`/data\` in the Docker image. |
| \`FILARR_GATE_CONFIG\` | Path of a \`gate.toml\` elsewhere than in the state directory. |
| \`FILARR_GATE_EXTDB_<ID>\` | The key of an external database a sync definition names: \`<ID>\` is the first 8 characters after \`xs_\` of the definition id, in upper case. The exact name is shown on the **Sources** screen and by \`filarr-gate sources list\`. |
| \`FILARR_GATE_LOG_LEVEL\` | \`debug\`, \`info\` (default), \`warn\`, \`error\`. |
| \`FILARR_GATE_PUBLIC_URL\` | Cloudflare variant: the address to show and give out, when it is not the one requests arrive on. |
| \`FILARR_GATE_ADMIN_URL\` | Command line: the management UI of a gate on another machine (same as \`--remote\`). |
| \`FILARR_GATE_URL\`, \`FILARR_GATE_KEY\` | \`filarr-gate mcp\`: the local API to relay to, and the app key to use (same as \`--gate\` and \`--key\`). |
| \`FILARR_GATE_NEW_TOKEN\` | \`filarr-gate export\`: the token of the gate that takes over (same as \`--for-token\`). |

## \`gate.toml\`

\`\`\`toml
# $FILARR_GATE_STATE_DIR/gate.toml
port = 8443
write = true
cors_origins = ["https://shop.example.com"]
trust_proxy = ["127.0.0.1"]
files_allow = [".pdf", ".csv", ".xlsx"]

# The key of an external database, by sync definition id (never sent to Filarr)
[extdb."xs_AbCdEfGhIjKlMnOpQrStUv"]
secret = "…"
\`\`\`

Only a subset of TOML is read: \`key = value\` (string, number, boolean, array of strings), \`[section]\` headers, and \`#\` comments.
`;
}

// ==================== Ligne de commande ====================

/** Les descriptions en anglais des commandes de `filarr-gate --help`, par leurs premiers mots. */
const COMMAND_TEXT: Record<string, string> = {
  'filarr-gate [serve]': 'Start the local API and the management UI (the default command).',
  'filarr-gate init': 'Store the token (file mode 0600) and the given settings, then stop. `--import FILE` applies a settings package (migration). Refused while a gate runs on the same state directory.',
  'filarr-gate health': 'Probe `/health` of the local API on this machine; exit 0 when it answers 200 (the Docker health check).',
  'filarr-gate doctor': 'Diagnose without changing anything: clock, Filarr, token, creator key, databases and keys, quotas, files, syncs. Exit 1 when a check fails.',
  'filarr-gate version': 'Print the version.',
  'filarr-gate keys create': 'Create an app key that reads every view (`--sql`: SQL too; `--mcp`: MCP; `--files`: file deposits; `--rate`: requests per minute; `--days`: expiry). The key is printed once. Narrower keys (one database, one view, writes) are made in the management UI.',
  'filarr-gate keys list': 'List the app keys (prefix, name, pause, expiry).',
  'filarr-gate keys revoke': 'Revoke a key by its id or the start of its prefix; it stops working at once.',
  'filarr-gate sources list': 'List the external syncs Filarr assigns to this gate, what blocks each one, and where its key comes from.',
  'filarr-gate sources key': 'Give (or clear) the key of an external database; `--stdin` keeps it out of the shell history. Stored encrypted under a key derived from the token.',
  'filarr-gate sources run': 'Run a sync pass now. `--ack-guard PASS` agrees to a stopped pass (safety stop), for that pass only; `--initial source|filarr` settles a first pass that hit too many conflicts.',
  'filarr-gate sources pause': 'Pause a sync on this gate (`sources resume` resumes it). The definition stays in Filarr.',
  'filarr-gate files test': 'Deposit a small test file into the linked deposit box.',
  'filarr-gate files status': 'The status of a deposit (`deposited`, `filed`, `rejected`, `expired`).',
  'filarr-gate export': 'Seal this gate\'s settings (app keys, webhooks, saved queries, sync state, file filter) for the gate that takes over, identified by its new token.',
  'filarr-gate import': 'Apply a sealed settings package made for this gate\'s token.',
  'filarr-gate mcp': 'An MCP server over stdio, for AI assistants that launch a command: it relays to `POST /mcp` of a running gate, with an app key that has the MCP right.',
};

function cliHelp(): string {
  const fake = resolve('/home/you/.filarr-gate');
  const res = spawnSync(process.execPath, [join(ROOT, 'node_modules', 'tsx', 'dist', 'cli.mjs'), join(ROOT, 'packages', 'cli', 'src', 'cli.ts'), '--help'], {
    cwd: ROOT,
    env: { ...process.env, FILARR_GATE_STATE_DIR: fake },
    encoding: 'utf8',
  });
  if (res.status !== 0) throw new Error(`filarr-gate --help failed: ${res.stderr}`);
  return res.stdout.split(fake).join('~/.filarr-gate').replace(/^Filarr Gate \S+ /, 'Filarr Gate <version> ').replace(/\r\n/g, '\n').trimEnd();
}

/** Les commandes du texte d'aide : les lignes qui commencent par `  filarr-gate`. */
function helpCommands(help: string): string[] {
  const out: string[] = [];
  for (const line of help.split('\n')) {
    const m = /^ {2}(filarr-gate (?:\[serve\]|[a-z]+(?: [a-z]+)?))/.exec(line);
    if (!m) continue;
    let cmd = m[1]!;
    // Seules les sous-commandes qui sont des mots de l'aide (`keys create`), pas leurs arguments
    const [, first, second] = cmd.split(' ');
    if (second && !['keys', 'sources', 'files'].includes(first!)) cmd = `filarr-gate ${first}`;
    if (!out.includes(cmd)) out.push(cmd);
    // `sources pause DEF_ID | sources resume DEF_ID` nomme deux commandes sur une ligne
    if (/\| sources resume/.test(line) && !out.includes('filarr-gate sources resume')) out.push('filarr-gate sources resume');
  }
  return out;
}

function cliMd(help: string, problems: string[]): string {
  const cmds = helpCommands(help);
  for (const c of cmds) if (c !== 'filarr-gate sources resume' && !COMMAND_TEXT[c]) problems.push(`docs/reference/cli.md: the command « ${c} » of the help has no description in scripts/docs/build.ts`);
  for (const c of Object.keys(COMMAND_TEXT)) if (!cmds.includes(c)) problems.push(`docs/reference/cli.md: « ${c} » is described but is no longer in the help`);
  const usage = (c: string): string => {
    const line = help.split('\n').find((l) => l.startsWith(`  ${c}`)) ?? c;
    return line.trim().replace(/\s{2,}.*$/, '');
  };
  const rows = cmds.filter((c) => COMMAND_TEXT[c]).map((c) => `| \`${usage(c).replace(/\|/g, '\\|')}\` | ${COMMAND_TEXT[c]} |`);
  return `<!-- Generated by \`npm run docs\` from \`filarr-gate --help\` (packages/cli/src/cli.ts): do not edit by hand. -->

# Command line: \`filarr-gate\`

\`\`\`sh
npx filarr-gate <command> [options]       # once published on npm
node packages/cli/dist/cli.js <command>   # from a clone, after npm ci && npm run build
docker exec <container> filarr-gate <command>
\`\`\`

## Commands

| command | what it does |
|---|---|
${rows.join('\n')}

## Common options

| option | |
|---|---|
| \`--json\` | Print JSON that a program can read, for every command. Errors become \`{ "error", "code" }\`. |
| \`--remote URL\` | Act on a gate of ANOTHER machine through its management UI, with \`--admin-password\` (or \`FILARR_GATE_ADMIN_PASSWORD\`). |
| \`--help\` | Print the help below. |

## Where a command acts

1. **A gate running on this state directory** (\`docker exec\` included): the command goes through it, without a password. A running gate writes \`cli.json\` (mode 0600) in its state directory with the secret of this channel, which only answers on the loopback address; whoever can read that directory already holds the token.
2. **\`--remote URL\`**: through the management UI of a gate on another machine, with its password.
3. **Otherwise**: the command opens the gate's state for the time of the gesture (no port, no scheduled sync), then stops. A key created this way reaches a gate that runs elsewhere on the same state only after its restart; prefer \`--remote\`.

Exit codes: \`0\` success, \`1\` failure (and \`doctor\` with a failed check), \`2\` wrong usage.

## The help, as printed

The command line speaks French for now; the table above gives each command in English.

\`\`\`text
${help}
\`\`\`
`;
}

// ==================== Codes ====================

const esc = (s: string): string => s.replace(/\|/g, '\\|');
const remedyText = (r: string[] | 'by-reason' | null | undefined, asleep: Record<string, string[] | null>): string => {
  if (r === 'by-reason') return Object.entries(asleep).map(([k, v]) => `${k}: ${v ? v.map((x) => `\`${x}\``).join(', ') : 'none'}`).join('; ');
  return r && r.length > 0 ? r.map((x) => `\`${x}\``).join(', ') : '';
};

function errorsMd(problems: string[]): string {
  const local = localApiCodes();
  for (const code of local.keys()) if (!LOCAL_CODES[code] && !BASE_PROBLEMS[code]) problems.push(`docs/reference/errors.md: the code « ${code} » of the local API is not explained in scripts/docs/codes.ts`);
  for (const code of Object.keys(LOCAL_CODES)) if (!local.has(code)) problems.push(`docs/reference/errors.md: « ${code} » is explained but no longer exists in the code`);
  for (const [code, t] of Object.entries(LOCAL_CODES)) {
    if (!t.byStatus) continue;
    for (const s of local.get(code) ?? []) if (!t.byStatus[s]) problems.push(`docs/reference/errors.md: « ${code} » has no explanation for its status ${s}`);
  }
  const localRows: string[] = [];
  for (const code of [...local.keys()].sort()) {
    const t = LOCAL_CODES[code];
    if (!t) continue;
    const statuses = [...local.get(code)!].sort();
    if (t.byStatus) for (const s of statuses) localRows.push(`| \`${code}\` | ${s} | ${esc(t.byStatus[s]!.what)} | ${esc(t.byStatus[s]!.fix)} |`);
    else localRows.push(`| \`${code}\` | ${statuses.join(', ')} | ${esc(t.what)} | ${esc(t.fix)} |`);
  }
  const bases = baseProblemCodes();
  for (const c of bases) if (!BASE_PROBLEMS[c]) problems.push(`docs/reference/errors.md: the base problem « ${c} » is not explained`);
  for (const c of Object.keys(BASE_PROBLEMS)) if (!bases.includes(c)) problems.push(`docs/reference/errors.md: the base problem « ${c} » no longer exists in the code`);
  const links = linkStates();
  for (const c of links) if (!LINK_STATES[c]) problems.push(`docs/reference/errors.md: the link state « ${c} » is not explained`);
  for (const c of Object.keys(LINK_STATES)) if (!links.includes(c)) problems.push(`docs/reference/errors.md: the link state « ${c} » no longer exists in the code`);
  const sync = syncCodes();
  for (const c of sync) if (!SYNC_CODES[c]) problems.push(`docs/reference/errors.md: the sync code « ${c} » is not explained`);
  const contractOnly = ['extdb_relay_limited', 'extdb_web_unsupported'];
  for (const c of Object.keys(SYNC_CODES)) if (!sync.includes(c) && !contractOnly.includes(c)) problems.push(`docs/reference/errors.md: the sync code « ${c} » no longer exists in the code`);
  const { rows, asleep } = vectorCodes();
  for (const r of rows) if (!FILARR_REV3[r.code]) problems.push(`docs/reference/errors.md: the Filarr code « ${r.code} » of the vectors is not explained`);
  for (const c of Object.keys(FILARR_REV3)) if (!rows.some((r) => r.code === c)) problems.push(`docs/reference/errors.md: « ${c} » is explained as a revision 3 code but is not in the vectors`);

  const table = (head: string, lines: string[]) => `${head}\n${lines.join('\n')}`;
  return `<!-- Generated by \`npm run docs\` from the code (packages/gate, packages/server) and the vectors test/vectors/boite-noire-v2-serveur.vectors.json: do not edit by hand; the explanations live in scripts/docs/codes.ts. -->

# Error codes and states

Every refusal of the local API is JSON: \`{ "error": "<message>", "code": "<code>", … }\`. **Match on \`code\`**: it is stable; \`error\` is a message for people (in French for now) and may change. A \`429\` carries \`Retry-After\` (seconds).

For the steps to follow by symptom, see [troubleshooting.md](../troubleshooting.md).

- [Codes of the local API](#codes-of-the-local-api)
- [Codes passed on from Filarr](#codes-passed-on-from-filarr)
- [Why a database is not served](#why-a-database-is-not-served)
- [The link with Filarr](#the-link-with-filarr)
- [What Filarr answers the gate](#what-filarr-answers-the-gate)
- [States of an external sync](#states-of-an-external-sync)

## Codes of the local API

Codes the gate itself returns to your software (and, marked "Admin", its management API).

${table('| code | status | what happened | what to do |\n|---|---|---|---|', localRows)}

## Codes passed on from Filarr

When Filarr refuses a write or a file deposit, the local API returns Filarr's \`code\` and status unchanged: ${PASSED_THROUGH.map((c) => `\`${c}\``).join(', ')}. They are explained [below](#what-filarr-answers-the-gate). Any other refusal of Filarr becomes \`502\` with Filarr's code.

## Why a database is not served

Until a database is complete and verified, its routes answer \`503\` with one of these codes. Once it has been served, a later problem does not stop it: the gate keeps serving its last complete copy and adds the header \`X-Gate-Base-Status\`.

${table(
  '| code | what happened | what to do |\n|---|---|---|',
  Object.entries(BASE_PROBLEMS).map(([c, t]) => `| \`${c}\` | ${esc(t.what)} | ${esc(t.fix)} |`)
)}

## The link with Filarr

\`GET /health\` returns it as \`link\`; the management UI and \`filarr-gate doctor\` show it; the library returns it in \`status().link\`.

${table(
  '| state | what it means | what to do |\n|---|---|---|',
  links.map((c) => `| \`${c}\` | ${esc(LINK_STATES[c]?.what ?? '')} | ${esc(LINK_STATES[c]?.fix ?? '')} |`)
)}

## What Filarr answers the gate

The gate handles these by itself; you see them in its log, in \`filarr-gate doctor\`, and passed on for writes and deposits. Revision 3 codes come with a **remedy** (the vocabulary Filarr's apps use to propose a gesture: \`upgrade\`, \`wait\`, \`reauthenticate\`, \`manageBilling\`, \`updatePayment\`).

${table(
  '| code | status | what happened | what the gate does | what to do |\n|---|---|---|---|---|',
  Object.entries(FILARR_REV2).map(([c, t]) => `| \`${c}\` | ${t.status} | ${esc(t.what)} | ${esc(t.gate)} | ${esc(t.fix)} |`)
)}

Revision 3 (hosted box, files, external syncs), read from the vectors:

${table(
  '| code | status | remedy | `Retry-After` | what happened | what to do |\n|---|---|---|---|---|---|',
  rows.map((r) => {
    const t = FILARR_REV3[r.code];
    return `| \`${r.code}\` | ${r.status} | ${remedyText(r.remedy, asleep)} | ${r.retryAfter ? 'yes' : ''} | ${esc(t?.what ?? '')}${t?.gate ? ` Gate: ${esc(t.gate)}` : ''} | ${esc(t?.fix ?? '')} |`;
  })
)}

## States of an external sync

The gate publishes the state of each sync it runs (sealed: Filarr cannot read it; the members of the database can). These codes appear in that state, in the **Sources** screen and in \`filarr-gate sources list\`; never as an HTTP status. Codes marked "web only" concern syncs run by the Filarr web app.

${table(
  '| code | what happened | what to do |\n|---|---|---|',
  Object.entries(SYNC_CODES).map(([c, t]) => `| \`${c}\` | ${esc(t.what)} | ${esc(t.fix)} |`)
)}
`;
}

// ==================== Dépannage : les sections générées ====================

function vectorTable(lang: 'en' | 'fr', problems: string[]): string {
  const { rows, asleep } = vectorCodes();
  const lines: string[] = [];
  for (const r of rows) {
    const t: CodeText | undefined = lang === 'en' ? FILARR_REV3[r.code] : FILARR_REV3_FR[r.code];
    if (!t) {
      problems.push(`troubleshooting (${lang}): « ${r.code} » has no text`);
      continue;
    }
    lines.push(`| \`${r.code}\` | ${r.status} | ${remedyText(r.remedy, asleep)}${r.retryAfter ? (lang === 'en' ? ' (with `Retry-After`)' : ' (avec `Retry-After`)') : ''} | ${esc(t.what)} | ${esc(t.fix)} |`);
  }
  if (lang === 'fr') for (const c of Object.keys(FILARR_REV3_FR)) if (!rows.some((r) => r.code === c)) problems.push(`troubleshooting (fr): « ${c} » is not in the vectors`);
  const head = lang === 'en' ? '| code | status | remedy | what happened | what to do |' : '| code | statut | remède | ce qui s’est passé | que faire |';
  return `${head}\n|---|---|---|---|---|\n${lines.join('\n')}`;
}

function linkTable(lang: 'en' | 'fr', problems: string[]): string {
  const states = linkStates();
  const texts = lang === 'en' ? LINK_STATES : LINK_STATES_FR;
  for (const s of states) if (!texts[s]) problems.push(`troubleshooting (${lang}): the link state « ${s} » has no text`);
  const head = lang === 'en' ? '| state | what it means | what to do |' : '| état | ce que cela veut dire | que faire |';
  return `${head}\n|---|---|---|\n${states.map((s) => `| \`${s}\` | ${esc(texts[s]?.what ?? '')} | ${esc(texts[s]?.fix ?? '')} |`).join('\n')}`;
}

/** Remplace le contenu entre `<!-- generated:NOM -->` et `<!-- /generated:NOM -->`. */
function fillSections(text: string, file: string, sections: Record<string, string>, problems: string[]): string {
  let out = text;
  for (const [name, body] of Object.entries(sections)) {
    const re = new RegExp(`(<!-- generated:${name} -->)\\n(?:[\\s\\S]*?\\n)?(<!-- /generated:${name} -->)`);
    if (!re.test(out)) {
      problems.push(`${file}: the section « generated:${name} » is missing`);
      continue;
    }
    out = out.replace(re, (_m, a: string, b: string) => `${a}\n${body}\n${b}`);
  }
  return out;
}

// ==================== Les blocs recopiés d'examples/ ====================

/** Les lignes entre les commentaires `region NOM` et `endregion` d'un fichier (toute syntaxe de commentaire), désindentées. */
export function region(file: string, name: string): string | null {
  const lines = readFileSync(join(ROOT, file), 'utf8').replace(/\r\n/g, '\n').split('\n');
  const start = lines.findIndex((l) => new RegExp(`(#|//|--|<!--)\\s*region ${name}\\b`).test(l));
  if (start < 0) return null;
  const end = lines.findIndex((l, i) => i > start && /(#|\/\/|--|<!--)\s*endregion\b/.test(l));
  if (end < 0) return null;
  const body = lines.slice(start + 1, end).filter((l) => !/(#|\/\/|--|<!--)\s*(end)?region\b/.test(l));
  const indent = Math.min(...body.filter((l) => l.trim() !== '').map((l) => /^ */.exec(l)![0].length));
  return body.map((l) => l.slice(Number.isFinite(indent) ? indent : 0)).join('\n').trimEnd();
}

function fillSnippets(text: string, file: string, problems: string[]): string {
  return text.replace(/(<!-- snippet: ([^\s#]+)(?:#([A-Za-z0-9_-]+))? -->\n```[^\n]*\n)([\s\S]*?)(\n```)/g, (all, head: string, src: string, name: string | undefined, _body: string, tail: string) => {
    if (!existsSync(join(ROOT, src))) {
      problems.push(`${file}: snippet of a missing file ${src}`);
      return all;
    }
    const content = name ? region(src, name) : readFileSync(join(ROOT, src), 'utf8').replace(/\r\n/g, '\n').trimEnd();
    if (content === null) {
      problems.push(`${file}: no region « ${name} » in ${src}`);
      return all;
    }
    return `${head}${content}${tail}`;
  });
}

// ==================== Contrôles des pages écrites ====================

function markdownFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string) => {
    for (const n of readdirSync(dir)) {
      if (n === 'node_modules' || n === 'dist' || n.startsWith('.')) continue;
      const p = join(dir, n);
      if (statSync(p).isDirectory()) walk(p);
      else if (n.endsWith('.md')) out.push(p);
    }
  };
  walk(join(ROOT, 'docs'));
  walk(join(ROOT, 'examples'));
  for (const f of ['README.md', 'README.fr.md', 'SECURITY.md']) out.push(join(ROOT, f));
  return out;
}

/** Les ancres d'un fichier Markdown, comme GitHub les fabrique. */
function anchors(text: string): Set<string> {
  const out = new Set<string>();
  const seen = new Map<string, number>();
  for (const m of text.replace(/```[\s\S]*?```/g, '').matchAll(/^#{1,6} (.+)$/gm)) {
    const base = m[1]!
      .trim()
      .toLowerCase()
      .replace(/[`*_]/g, '')
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/[^\p{L}\p{N}\s-]/gu, '')
      .replace(/ /g, '-');
    const n = seen.get(base) ?? 0;
    seen.set(base, n + 1);
    out.add(n === 0 ? base : `${base}-${n}`);
  }
  return out;
}

/** Les mots qui feraient d'un quota de palier un chiffre écrit à la main. */
const QUOTA_NUMBER = /\b\d[\d  ,.]*\s*(?:requests?|requêtes?|writes?|écritures?|commits?|validations?|files?|fichiers?|GB|GiB|Go)\s*(?:\/|per|par|a|an|each)\s*(?:month|mois|day|jour|minute)\b/i;

function lint(files: string[], problems: string[]): void {
  const envNames = knownEnvNames();
  for (const f of files) {
    const text = readFileSync(f, 'utf8');
    const name = rel(f);
    for (const m of text.matchAll(/FILARR_GATE_[A-Z0-9_]+(?:<ID>)?/g)) {
      const v = m[0].startsWith('FILARR_GATE_EXTDB_') && !envNames.has(m[0]) ? 'FILARR_GATE_EXTDB_<ID>' : m[0];
      if (v === 'FILARR_GATE_EXTDB_' || v === 'FILARR_GATE_EXTDB_<ID>' || envNames.has(v)) continue;
      problems.push(`${name}: the variable ${m[0]} does not exist in the code`);
    }
    const prose = text.replace(/```[\s\S]*?```/g, '');
    const q = QUOTA_NUMBER.exec(prose);
    if (q) problems.push(`${name}: a plan quota written as a number (« ${q[0]} »): say where to read it instead (GET /public/api-limits, Usage and limits)`);
    for (const m of prose.matchAll(/\[[^\]]*\]\(([^)\s]+)\)/g)) {
      const target = m[1]!;
      if (/^(https?:|mailto:)/.test(target)) continue;
      const [path, hash] = target.split('#') as [string, string | undefined];
      const file = path === '' ? f : resolve(dirname(f), decodeURIComponent(path));
      if (!existsSync(file)) {
        problems.push(`${name}: link to a missing file ${target}`);
        continue;
      }
      if (hash && file.endsWith('.md') && !anchors(readFileSync(file, 'utf8')).has(hash)) problems.push(`${name}: link to a missing anchor ${target}`);
    }
  }
}

// ==================== Exécution ====================

export interface DocsResult {
  /** Les fichiers dont le contenu diffère de ce qui serait généré. */
  changed: string[];
  /** Tout le reste de ce qui ne va pas. */
  problems: string[];
}

export function buildDocs(opts: { check: boolean }): DocsResult {
  const problems: string[] = [];
  const outputs = new Map<string, string>();
  outputs.set('docs/reference/configuration.md', configurationMd());
  outputs.set('docs/reference/cli.md', cliMd(cliHelp(), problems));
  outputs.set('docs/reference/errors.md', errorsMd(problems));
  const codes = [...localApiCodes().keys()].sort();
  outputs.set('docs/openapi/filarr-gate.v1.json', `${JSON.stringify(genericOpenApi(codes), null, 2)}\n`);

  // Les fichiers à sections générées, et chaque page à blocs recopiés
  const files = markdownFiles();
  for (const f of files) {
    const name = rel(f);
    if (outputs.has(name)) continue;
    let text = readFileSync(f, 'utf8').replace(/\r\n/g, '\n');
    if (/troubleshooting(\.fr)?\.md$/.test(name)) {
      const lang = name.endsWith('.fr.md') ? 'fr' : 'en';
      text = fillSections(text, name, { 'filarr-codes': vectorTable(lang, problems), 'link-states': linkTable(lang, problems) }, problems);
    }
    text = fillSnippets(text, name, problems);
    outputs.set(name, text);
  }

  const changed: string[] = [];
  for (const [name, content] of outputs) {
    const file = join(ROOT, name);
    const now = existsSync(file) ? readFileSync(file, 'utf8').replace(/\r\n/g, '\n') : null;
    if (now === content) continue;
    changed.push(name);
    if (!opts.check) {
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, content);
    }
  }
  lint(markdownFiles(), problems);
  return { changed, problems };
}

if (process.argv[1] && resolve(process.argv[1]) === resolve(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'))) {
  const check = process.argv.includes('--check');
  const { changed, problems } = buildDocs({ check });
  if (check && changed.length > 0) problems.unshift(...changed.map((c) => `${c}: differs from what \`npm run docs\` generates`));
  if (problems.length > 0) {
    process.stderr.write(`${problems.length} problem(s):\n${problems.map((p) => `  - ${p}`).join('\n')}\n`);
    process.exit(1);
  }
  process.stdout.write(check ? 'documentation: up to date\n' : `documentation: ${changed.length} file(s) written${changed.length ? `\n${changed.map((c) => `  ${c}`).join('\n')}` : ''}\n`);
}
